<?php
/** @var \RealThanks\GiftProvider\Block\Adminhtml\System\Config\Updater $block */
?>
<script type="text/javascript">
    require(["jquery"], function () {
    });

    function updateData() {
        jQuery.ajax({
            type: "GET",
            showLoader: true,
            data: {},
            url: '<?= /* @noEscape */ $block->getDataUpdaterUrl() ?>',
            success: function (result, status) {
                if (result.ajaxExpired) {
                    window.location = result.ajaxRedirect;
                } else {
                    location.reload();
                }
            },
            error: function () {
                location.reload();
            },
            dataType: "json"
        });
        return false;
    }

</script>

<?php
$balanceTxt = __('Current account balance: ');
if ($block->getLatestSyncLogDate() === null) {
    $class = 'rt-message-notice';
    $generalMessage = '';
    $message = __('No previous synchronizations with RealThanks found');
} else {
    $generalMessage = __('Last synchronization: ');
    if ($block->isSuccessful()) {
        $class = 'rt-message-success';
        $message = __('%1 UTC was successful', $block->getLatestSyncLogDate());
    } else {
        $class = 'rt-message-error';
        $message = __(
            'for %1 at %2 UTC was failed: %3',
            $block->getLogErrorType(),
            $block->getLogErrorDate(),
            $block->getLogErrorMessage()
        );
    }
}
?>
<div class="rt-gift-message-container">
    <div><b><?= /* @noEscape */ $balanceTxt ?></b><?= /* @noEscape */ $block->getCurrentBalance() ?></div>
    <div class="<?= /* @noEscape */ $class ?>">
        <b><?= /* @noEscape */ $generalMessage ?></b><?= /* @noEscape */ $message ?></div>
    <button name="load_data" onclick="return updateData();">
        <?= /* @noEscape */ __('Update RealThanks data') ?></button>
</div>
