<?php
/** @var \RealThanks\GiftProvider\Block\Adminhtml\System\Config\Updater $block */
?>
<script type="text/javascript">
    //just to load jQuery on this page
    require(["jquery"], function () {
    });

    function updateData() {
        jQuery.ajax({
            type: "GET",
            showLoader: true,
            data: {},
            url: '<?= /* @noEscape */ $block->getDataUpdaterUrl() ?>',
            success: function (result, status) {
                if (result.ajaxExpired) {
                    window.location = result.ajaxRedirect;
                } else {
                    location.reload();
                }
            },
            error: function () {
                location.reload();
            },
            dataType: "json"
        });
        return false;
    }

</script>
<button name="load_data" onclick="return updateData();"><?= /* @noEscape */ __('Update RealThanks data') ?></button>
<?php
$balance = __('Current account balance - %1', $block->getCurrentBalance());
if ($block->getLatestSyncLogDate() === null) {
    $class = 'message-notice';
    $message = __('No previous synchronizations with RealThanks found');
} else {
    if ($block->isSuccessful()) {
        $class = 'message-success';
        $message = __('Last synchronization at %1 UTC was successful', $block->getLatestSyncLogDate());
    } else {
        $class = 'message-error';
        $message = __(
            'Last %1 synchronization at %2 UTC was failed: %3',
            $block->getLogErrorType(),
            $block->getLogErrorDate(),
            $block->getLogErrorMessage()
        );
    }
}
?>
<div class="message <?= /* @noEscape */ $class ?>" data-ui-id="sync-status"><?= /* @noEscape */ $message ?></div>
<div class="message message-balance" ><?= /* @noEscape */ $balance ?></div>
